# add asdf to path
export ASDF_DATA_DIR="$HOME/.asdf";

# dir for python simlink
export PATH="$HOME/.bin:$PATH"

# install zinit
ZINIT_HOME="$HOME/.local/share/zinit/zinit.git"
[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
source "$ZINIT_HOME/zinit.zsh"
zinit ice lucid depth"1" blockf
zinit light yuki-yano/zeno.zsh

# ########################################
# zeno
# ########################################
# git file preview with color
export ZENO_GIT_CAT="bat --color=always"

# git folder preview with color
export ZENO_GIT_TREE="eza --tree"

if [[ -n $ZENO_LOADED ]]; then
bindkey ' '  zeno-auto-snippet

bindkey '^m' zeno-auto-snippet-and-accept-line

bindkey '^i' zeno-completion

bindkey '^x '  zeno-insert-space
bindkey '^x^m' accept-line
bindkey '^x^z' zeno-toggle-auto-snippet

bindkey '^r' zeno-smart-history-selection # smart history widget
fi

# wezterm shell integration
source "$HOME/.config/wezterm/wezterm.sh"
